steps:

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-ssh-key > /root/.ssh/id_rsa" ]

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-terminus-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > terminus-token.txt" ]

- name: octahedroid/pantheon-gcp-builder
  entrypoint: bash
  args:
  - -c
  - |
    /build-tools-ci/scripts/set-environment
    export TERMINUS_TOKEN=$(cat terminus-token.txt)
    (
      echo "export TERMINUS_TOKEN='$$TERMINUS_TOKEN'"
    ) >> $$BASH_ENV
    
  # args: ['/build-tools-ci/scripts/set-environment']
  env:
  - 'CI_BRANCH=$_HEAD_BRANCH'
  - 'CI_BUILD_NUMBER=$_PR_NUMBER'
  - 'PR_NUMBER=$_PR_NUMBER'
  - 'CI_PULL_REQUEST=$_HEAD_REPO_URL'
  - 'DEFAULT_SITE=$_TERMINUS_SITE'
  - 'BASH_ENV=/workspace/build_vars'

- name: octahedroid/pantheon-gcp-builder
  entrypoint: bash
  args:
  - -c
  - |
    source /workspace/build_vars
    echo $$TERMINUS_TOKEN
    terminus -n auth:login --machine-token="$$TERMINUS_TOKEN"    

- name: octahedroid/pantheon-gcp-builder
  entrypoint: bash
  args:
  - -c
  - |
    source /workspace/build_vars
    chmod 600 /root/.ssh/id_rsa
    # cat <<EOF >/root/.ssh/config
    # Hostname drush.in
    # IdentityFile /root/.ssh/id_rsa
    # EOF
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    # Ensure that there's a Pantheon repo locally. If one was not
    # restored from cache, clone it fresh.
    if [ ! -d "$$PANTHEON_REPO_DIR/.git" ]; then
      cd $$PANTHEON_REPO_DIR
      git init
      git remote add pantheon $(terminus connection:info $$TERMINUS_SITE.dev --field=git_url)
      git remote -v
    fi
    git fetch pantheon
    
    # If the current branch is on Pantheon, check it out.
    # If it is not, checkout master and then make a new branch.
    if git ls-remote pantheon | grep "refs/heads/$$TERMINUS_ENV$" > /dev/null; then
      git checkout $$TERMINUS_ENV
      git pull
    else
      git checkout master
      git pull
      git checkout -b $$TERMINUS_ENV
    fi
    ls -la $$PANTHEON_REPO_DIR
    
  env:
  - 'PANTHEON_REPO_DIR=/workspace/pantheon_repo'  

options:
  volumes:
  - name: 'ssh'
    path: /root/.ssh
  - name: 'pantheon_repo'
    path: /workspace/pantheon_repo