steps:
- name: 'bash'
  args: ['echo', 'I am running a bash command']

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-ssh-key > /root/.ssh/id_rsa" ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-terminus-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > terminus-token.txt" ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: quay.io/pantheon-public/build-tools-ci:6.x
  entrypoint: bash
  args:
  - -c
  - |
    export TERMINUS_MACHINE_TOKEN=$(cat terminus-token.txt) &&
    /build-tools-ci/scripts/set-environment
  # args: ['/build-tools-ci/scripts/set-environment']
  env:
  - 'CI_BRANCH=$_HEAD_BRANCH'
  - 'CI_BUILD_NUMBER=$_PR_NUMBER'
  - 'PR_NUMBER=$_PR_NUMBER'
  - 'CI_PULL_REQUEST=$_HEAD_REPO_URL'
  - 'DEFAULT_SITE=$_TERMINUS_SITE'
  volumes:
  - name: 'ssh'
    path: /root/.ssh
