steps:
- name: 'bash'
  args: ['echo', '$HOME']

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-ssh-key > /root/.ssh/id_rsa" ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', "gcloud secrets versions access latest --secret=gcb-wordpress-terminus-token --format='get(payload.data)' | tr '_-' '/+' | base64 -d > terminus-token.txt" ]
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# - id: "Store Values"
#   name: gcr.io/cloud-builders/curl
#   entrypoint: /bin/bash
#   args:
#     - -c 
#     - |
#       # store multiple values as environment variables
#       # name all values with a common prefix (we'll use "build_")
#       export build_firstname="Robin" &&
#       export build_lastname="Babbage" &&
#       export build_cookie="Snickerdoodle" &&
      
#       # write all "build_" variables to the persistent volume "/workspace"
#       env | grep "^build_" > /workspace/build_vars

- name: octahedroid/pantheon-gcp-builder
  entrypoint: bash
  args:
  - -c
  - |
    cat terminus-token.txt
    export TERMINUS_TOKEN=$(cat terminus-token.txt)
    echo "terminus token from env $$TERMINUS_TOKEN"
    env | grep "^TERMINUS_"
    /build-tools-ci/scripts/set-environment
    
  # args: ['/build-tools-ci/scripts/set-environment']
  env:
  - 'CI_BRANCH=$_HEAD_BRANCH'
  - 'CI_BUILD_NUMBER=$_PR_NUMBER'
  - 'PR_NUMBER=$_PR_NUMBER'
  - 'CI_PULL_REQUEST=$_HEAD_REPO_URL'
  - 'DEFAULT_SITE=$_TERMINUS_SITE'
  - 'BASH_ENV=/workspace/build_vars'
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: octahedroid/pantheon-gcp-builder
  entrypoint: bash
  args:
  - -c
  - |
    source /workspace/build_vars
    echo $TERMINUS_TOKEN
    terminus -n auth:login --machine-token="$TERMINUS_TOKEN"
    
  # # args: ['/build-tools-ci/scripts/set-environment']
  # env:
  # - 'CI_BRANCH=$_HEAD_BRANCH'
  # - 'CI_BUILD_NUMBER=$_PR_NUMBER'
  # - 'PR_NUMBER=$_PR_NUMBER'
  # - 'CI_PULL_REQUEST=$_HEAD_REPO_URL'
  # - 'DEFAULT_SITE=$_TERMINUS_SITE'
  # - 'BASH_ENV=build_vars.txt'
  volumes:
  - name: 'ssh'
    path: /root/.ssh